name: CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
      max-parallel: 5
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: abatilo/actions-poetry@v3
    - run: poetry install
    - run: poetry run pydocstyle ./spatial3d
    - run: poetry run pylint ./spatial3d
    - run: poetry run black --check .
    - run: python -m unittest
